"""Add RoomCompletion model

Revision ID: 716a53e202a4
Revises: 734cec193177
Create Date: 2025-05-11 17:43:05.807888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '716a53e202a4'
down_revision = '734cec193177'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room_completion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('room_name', sa.String(length=50), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('room_completion')
    # ### end Alembic commands ###
